# Generated by Django 4.2.11 on 2024-04-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCloud',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='link_url',
        ),
    ]
