# Generated by Django 5.0.4 on 2024-04-18 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_delete_wordcloud_remove_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 4, 34, 34, 572669, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
